server:
  port: 8888
  servlet:
    context-path: /sparrow
spring:
  application:
    name: sparrow-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
project:
  version: @project.version@
sparrow:
  auth:
    enabled: true
